services:
  fe:
    image: 554423627857.dkr.ecr.ap-northeast-2.amazonaws.com/ktb-17/fe:latest
    container_name: fe
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env